/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Progress.java
 *
 * Created on Jul 7, 2018, 11:59:59 AM
 */
package desainekspedisi;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author rxxxx
 */
public class Progress extends javax.swing.JFrame {
    Timer timer;
    ActionListener action;
    Login Lg;
    
    
    /** Creates new form Progress */
    public Progress() {
        initComponents();
        setLocationRelativeTo(this);
        act();
         Timer t = new Timer(2000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //JLabel timerLabel = new JLabel("Time Remaining 300 seconds", SwingConstants.CENTER);
                jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
                jLabel2.setVerticalAlignment(SwingConstants.CENTER);
                jLabel2.setText("Loading.");
                
            }
        });
         t.start();
         Timer u = new Timer(3000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //JLabel timerLabel = new JLabel("Time Remaining 300 seconds", SwingConstants.CENTER);
                jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
                jLabel2.setVerticalAlignment(SwingConstants.CENTER);
                jLabel2.setText("  Loading..");
                
            }
        });
        u.start();
         Timer v = new Timer(4000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //JLabel timerLabel = new JLabel("Time Remaining 300 seconds", SwingConstants.CENTER);
                jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
                jLabel2.setVerticalAlignment(SwingConstants.CENTER);
                jLabel2.setText("    Loading...");
                
            }
        });
        v.start();
        timer = new Timer(100,action);
        timer.start();
        getContentPane().setBackground(new java.awt.Color(255,204,51));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desainekspedisi/animated.gif"))); // NOI18N

        jLabel2.setText("Selamat Datang di Aplikasi REY-Express");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
        } catch (InstantiationException ex) {
            Logger.getLogger(Progress.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Progress.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Progress.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Progress().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    private void act() {
        action = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                jProgressBar1.setValue(jProgressBar1.getValue() +2);
                jProgressBar1.setStringPainted(true);
                if(jProgressBar1.getPercentComplete() == 1.00){
                    timer.stop();
                    Lg = new Login();
                    Lg.setVisible(true);
                    dispose();
                }
                
            }
            
        };
        this.dispose();
    }
}
